In [1]:
import numpy as np

In [2]:
np.array?

In [11]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [4]:
np.linspace?

In [13]:
np.linspace(10,50,21)  

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38., 40., 42., 44., 46., 48., 50.])

In [19]:
np.random.randn(4,1)

array([[-0.42676805],
       [ 0.09133846],
       [ 0.52779509],
       [ 1.73971434]])

In [20]:
np.random.random(5)

array([0.17729854, 0.07975504, 0.67288755, 0.55731421, 0.21953528])

In [21]:
b=np.array([1,2,3,4])
np.resize(b,3)

array([1, 2, 3])

In [40]:

x=np.array([[1,2,3,4],
          [2,3,4,7]])
y=x=np.array([[5,2,0,4],
          [2,0,4,1]])

In [41]:
np.delete(x,2,axis=1)

array([[5, 2, 4],
       [2, 0, 1]])

In [48]:
np.concatenate([x,y], axis=0)

array([[5, 2, 0, 4],
       [2, 0, 4, 1],
       [5, 2, 0, 4],
       [2, 0, 4, 1]])

In [51]:
np.hstack((x,y))

array([[5, 2, 0, 4, 5, 2, 0, 4],
       [2, 0, 4, 1, 2, 0, 4, 1]])

In [52]:
np.vstack((x,y))

array([[5, 2, 0, 4],
       [2, 0, 4, 1],
       [5, 2, 0, 4],
       [2, 0, 4, 1]])

In [73]:
h = np.arange(8)
np.array_split(h, 1,axis=0)

[array([0, 1, 2, 3, 4, 5, 6, 7])]

In [64]:
np.array_split?

In [74]:
y.flatten?

In [77]:
y.size*y.itemsize

64