In [3]:
import torch
import numpy as np

In [49]:
a=np.array([[1,2,3,4],[2,6,7,8]])

In [50]:
a

array([[1, 2, 3, 4],
       [2, 6, 7, 8]])

In [51]:
torch.is_tensor(a)

False

In [52]:
x=torch.from_numpy(a)

In [53]:
x

tensor([[1, 2, 3, 4],
        [2, 6, 7, 8]])

In [58]:
torch.is_tensor(x)

True

In [59]:
torch.tensor.View(x)

AttributeError: 'builtin_function_or_method' object has no attribute 'View'

In [19]:
x=x.numpy()

In [20]:
x

array([[1, 2, 3, 4],
       [2, 6, 7, 8]])

In [21]:
torch.randn(4)

tensor([-1.3319, -0.9283,  0.2976,  0.2396])

In [22]:
torch.randn((1,4))

tensor([[ 0.3383, -2.0466, -0.4520,  0.5771]])

In [23]:
torch.randn((1,4)).size()

torch.Size([1, 4])

In [24]:
np.empty(2)

array([-5.73021895e-300,  6.92600802e-310])

In [26]:
torch.empty(2)

tensor([1.6010e-37, 0.0000e+00])

In [29]:
b=np.array([[1,2,3,4],[2,6,7,8]])
b

array([[1, 2, 3, 4],
       [2, 6, 7, 8]])

In [28]:
torch.tensor(b)

tensor([[1, 2, 3, 4],
        [2, 6, 7, 8]])

In [60]:
x = torch.tensor([1, 2, 3, 4])
torch.unsqueeze(x, 0)

tensor([[1, 2, 3, 4]])

In [61]:
torch.squeeze(x)

tensor([1, 2, 3, 4])